# Generated by Django 4.1 on 2022-09-02 03:19

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='name',
            field=models.CharField(default=base.models.UserItem.name1, max_length=200),
        ),
    ]
