# Generated by Django 4.1 on 2022-09-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_useritem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='name',
        ),
        migrations.AddField(
            model_name='useritem',
            name='name1',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
