# Generated by Django 4.1 on 2022-09-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_useritem_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='useritem',
            name='size',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
